name: Build/release Electron app

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux -p always
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac -p always
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win -p always
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
